### ISSUE TITLE
iOS Keychain Error adding record: MissingEntitlement

### ISSUE THREAD

**Issue by steinbachio** [Aguafrommars/Maui.Blazor.Authentication#7]
First I wanna thank you for this library, it seems to be a very convenient way to implement oidc into maui blazor apps.

Unfortunately I get this Error after a valid signin.

```
Error adding record: MissingEntitlement
   at Microsoft.Maui.Storage.KeyChain.SetValueForKey(String value, String key, String service)
   at Microsoft.Maui.Storage.SecureStorageImplementation.SetAsync(String key, String value, SecAccessible accessible)
   at Microsoft.Maui.Storage.SecureStorageImplementation.PlatformSetAsync(String key, String data)
   at Microsoft.Maui.Storage.SecureStorageImplementation.SetAsync(String key, String value)
   at Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc.Services.AuthenticationStore.SetAsync(String scope, AuthenticationEntity value)
   at Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc.Services.OidcAuthenticationService`1.<StoreLoginResultAsync>d__16[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc.Services.OidcAuthenticationService`1.<SignInAsync>d__14[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<ProcessLogIn>d__85[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__84[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Either I missed it, or there is no part in the setup instructions about setting up the Keychain entitlements.

I tried to set them up, but i couldn't get around this error. Neither in my own solution, nor in the Example solution.

Any Ideas?

Best,
Marius

**Comment by steinbachio** [comment]
Finally got it working.
Unfortunately I'm not sure, what the issue was. After changing everything several times it seems like I got it working.

I'll leave this Issue open, as I think it would be good, to include this in the Sample.

**Comment by aguacongas** [comment]
This should help : https://learn.microsoft.com/en-us/answers/questions/1057290/when-running-the-(await-securestorage-setasync)-co

**Comment by aguacongas** [comment]
I added a *Entitlements.plist* to the sample, can you tell me if it works ?

**Comment by steinbachio** [comment]
I made it work with few modifications.

Adding this to Info.plist
```
    <key>CFBundleIdentifier</key>
    <string>com.companyname.maui-blazor</string>
```

And changing the string in Entitlements.plist to
```
    <string>$(AppIdentifierPrefix)com.companyname.maui-blazor</string>
```

Thats needed because to make it work, you need to create a empty project in Xcode with the same name, so provisioning profiles are created. Xcode will replace '.' in the projectsname with '-'.

Thank you for your fast response :-)

**Comment by steinbachio** [comment]
If you are going to mention this in the readme, its probably worth mentioning that i now have purchased an apple developer account. This was before i first made it successfully working, but i am not sure, if it makes a difference.
